### ISSUE TITLE
Ability for per-project overrides of FHIR service

### ISSUE THREAD

**Issue by andrewpatto** [aehrc/redcap_fhir_ontology_provider#4]
We currently have a setup where for a large shared Redcap installation (across a whole uni) - we want certain projects to be able to target a different ontoserver instance. 

So the site-wide FHIR_URL (which can be set to the NCTS ontoserver for instance) as a default is perfect - but for some specific project we would love to be able to override the ontoserver instance used (one department having its own custom valuesets and terminologies and hence using a custom ontoserver).

**Comment by dconlan** [comment]
When redcap does its autocomplete it uses a method on the ontology provider

```
  /**
   * Search API with a search term for a given ontology
   * Returns array of results with Notation as key and PrefLabel as value.
   */
  public function searchOntology($category, $search_term, $result_limit);
```

There is a caching mechanism which stores category, code, display so redcap doesn't need to use the remote service whenever it wants to show the display instead of the code. This module currently uses the FHIR valueset url as the category.

Because the searchOntology function doesn't reference a field id or a project id, I can't just adjust this routine. 

Instead I think I will need to change the way the category is stored to possible contain the fhir server url, or the project id. Using the fhir server url lets the caching span across projects, but it will increase the size of the category field, some implicit valueset urls can already be quite large. It will also mean the fhir server url is hardcoded in the field definition, so changing the url in the project settings would not change any existing fields, which would be very confusing.  We get a similar issue if we use project id, if we only add a project id if that project has a custom fhir server, nothing will keep the field settings and the external module settings in sync after the fact.

I'll have a think, maybe there is some other way of doing it.

**Comment by andrewpatto** [comment]
Thanks David for having a look/think - for the moment they appear to be happy with us changing the site-wide setting to our department ontoserver - but would be great to have a more general solution.

**Comment by dconlan** [comment]
I wrote a new external module to allow multiple FHIR servers.
It is now in the Redcap repository but it can be found here:

https://github.com/aehrc/redcap_advanced_fhir_ontology
